### ISSUE TITLE
Params validation

### ISSUE THREAD

**Issue by woltsu** [woltsu/telegram-orb#14]
Currently the commands assume that the env variables exist. Some validation would be neat.

**Comment by rmoswela** [comment]
I will take this one :-)

**Comment by rmoswela** [comment]
Hi @woltsu how would you like the validation to be handle. if the env var doesn't exist what happens

**Comment by woltsu** [comment]
I think that a clear warning message should be enough. We don't want the whole build to fail in my opinion.

**Comment by rmoswela** [comment]
@woltsu  i have been searching and i haven't found a way of doing this. Is there a resource that you can point me to that i can perhaps read that will help :-)

**Comment by woltsu** [comment]
For now I think that the solution would be to echo a warning message to the user if some of the parameters are empty or null. You need to expand the command itself in [here](https://github.com/woltsu/telegram-orb/blob/264608117d297602e9973e3ed70b5eb677e75641/src/commands/notify.yml#L33). Here's some discussion on how to figure out whether a variable is null/empty in bash: https://stackoverflow.com/questions/3061036/how-to-find-whether-or-not-a-variable-is-empty-in-bash

**Comment by rmoswela** [comment]
@woltsu i don't have a bot, is there a way i can test this locally before i do a PR? thanks by the way for the above guidance

**Comment by woltsu** [comment]
No problem! Unfortunately I have not found a way yet to test this locally. But, it's very easy to create a bot of your own by following the instructions on the bottom of the README file. Then, just add your own environmental variables into the CircleCI project configuration. More info about that here: https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project.

**Comment by woltsu** [comment]
There does seem to be a way to run circleci jobs locally, but I haven't familiarized myself with that yet: https://circleci.com/docs/2.0/local-cli/#run-a-job-in-a-container-on-your-machine

**Comment by rmoswela** [comment]
Awesome i will have to because i saw a couple of issues you raised that i would like to take a stab at

In the mean time i have created a PR check it and revert before i move to the other issues.
