### ISSUE TITLE
Possibility to send a gif

### ISSUE THREAD

**Issue by woltsu** [woltsu/telegram-orb#19]
It would be cool to be able to send gifs.

https://core.telegram.org/bots/api#sendanimation

**Comment by willumz** [comment]
Hi @woltsu, I'm new to CircleCI orbs but I reckon I could use your other commands as templates and have a go at this. Would the user specify the GIF URL as a parameter? And what would the default GIF URL be?

**Comment by woltsu** [comment]
Hey @Willumz! Yes, that's what I had in mind. I'm not 100% sure how Telegram handles the gif when given as url, so you should probably test that first. I think that the default url should be an empty string, and then there should be some validation so that the user is required to give the url if they want to use the command.

**Comment by woltsu** [comment]
Well done, thanks! @Willumz Feel free to add it to the README (in alpha branch) if you want. I can do that as well when I get the time.

**Comment by willumz** [comment]
Sure @woltsu, I can do that. I noticed #23 is practically identical to this one, should I replicate this code for that one as well?

**Comment by woltsu** [comment]
@Willumz Go for it! You could also add examples to both of the commands in the examples folder.
