### ISSUE TITLE
"sendSticker" command to send a sticker

### ISSUE THREAD

**Issue by woltsu** [woltsu/telegram-orb#24]
https://core.telegram.org/bots/api#sendsticker

**Comment by AMoldskred** [comment]
Mind if I have a go at this?

**Comment by woltsu** [comment]
@andreas0607 go for it! :)

**Comment by AMoldskred** [comment]
I made a pullrequest: [#29 ](https://github.com/woltsu/telegram-orb/pull/29) . I am pretty sure it works, however I didn't have time to test it. If anything is done wrong, I'd love to fix it. Just point me in the right direction (this is my first contribution to a CircleCI orb)

**Comment by woltsu** [comment]
@andreas0607 Thanks, I replied to your PR.

**Comment by woltsu** [comment]
Implemented https://github.com/woltsu/telegram-orb/pull/29
